// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxCcb0j2BkaILAw2Rbo57dl21sR5PkzM4',
    appId: '1:764395829073:web:1531235e2323a23e768570',
    messagingSenderId: '764395829073',
    projectId: 'task-1b945',
    authDomain: 'task-1b945.firebaseapp.com',
    storageBucket: 'task-1b945.firebasestorage.app',
    measurementId: 'G-J9KRNMTZPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArAwxfwUbkvQTQWrGVn97ufLixJEzP1aI',
    appId: '1:764395829073:android:38c196317ebf98f3768570',
    messagingSenderId: '764395829073',
    projectId: 'task-1b945',
    storageBucket: 'task-1b945.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBraWzfkm_zIqI_4w-aZ4Oj2pXmdEI-YCI',
    appId: '1:764395829073:ios:cb0a5838f3dabe9a768570',
    messagingSenderId: '764395829073',
    projectId: 'task-1b945',
    storageBucket: 'task-1b945.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBraWzfkm_zIqI_4w-aZ4Oj2pXmdEI-YCI',
    appId: '1:764395829073:ios:cb0a5838f3dabe9a768570',
    messagingSenderId: '764395829073',
    projectId: 'task-1b945',
    storageBucket: 'task-1b945.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxCcb0j2BkaILAw2Rbo57dl21sR5PkzM4',
    appId: '1:764395829073:web:dc6316e1dfcc81c3768570',
    messagingSenderId: '764395829073',
    projectId: 'task-1b945',
    authDomain: 'task-1b945.firebaseapp.com',
    storageBucket: 'task-1b945.firebasestorage.app',
    measurementId: 'G-BLJZ217L6V',
  );
}
